const videoList = [
    {
        name: 'Best of lofi hip hop 2021 ✨ [beats to relax/study to]',
        channel: 'Lofi Girl',
        verified: true,
        date: '1 year ago',
        duration: '6:32:05',
        link: `https://www.youtube.com/watch?v=n61ULEU7CO0`,
        thumbnail: `https://i.ytimg.com/vi/n61ULEU7CO0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAi4TCpAtbxLFIBULRlcZHudl1uFw`,
        channel_avatar: `https://yt3.ggpht.com/pcvnEbQ1F18Oms0Dn4qBf7APYU4Uj_AiJZAl023Z6ZBeSU7R8gq41DGMYgb1hBVhdK6GZeD6=s48-c-k-c0x00ffffff-no-rj`,
        views: '26M',
    },
    {
        name: `Relaxing Sleep Music with Rain Sounds | Cures for Anxiety Disorders, Piano Music, Calm Down & Relax`,
        channel: 'The Soul of Wind',
        verified: true,
        date: '2 months ago',
        duration: '23:06:02',
        link: `https://www.youtube.com/watch?v=VYJGMftYtY4`,
        thumbnail: `https://i.ytimg.com/vi/VYJGMftYtY4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAN6-_vwDTatvvzpeSNepd18T1eZA`,
        channel_avatar: `https://yt3.ggpht.com/ytc/AOPolaTABrRPPp31Z2AjTrUAiUanfpuzt2ZSdAGm04LuKA=s68-c-k-c0x00ffffff-no-rj`,
        views: '470K',
    },
    {
        name: `Relax Day 🌳 Lofi Keep You Safe 🍃 Lofi Hip Hop Radio ~ Chill Mix [Relax - Calm - Chill ]`,
        channel: 'LOFI KEEP YOU SAFE',
        verified: false,
        date: '2 months ago',
        duration: '11:55:56',
        link: `https://www.youtube.com/watch?v=9qM9YGI-XbM`,
        thumbnail: `https://i.ytimg.com/vi/9qM9YGI-XbM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrQEocKxp6iV0wO_L0paxUEKVLLQ`,
        channel_avatar: `https://yt3.ggpht.com/XDY_UbfPTh8MaRSFAihPDdHnjwDR4Qwx7XHJYBpGNrrztOKqD2VTbmzy8gu9vaTOkHeBMuRqfUo=s68-c-k-c0x00ffffff-no-rj`,
        views: '19K',
    },
    {
        name: 'Best of lofi hip hop 2021 ✨ [beats to relax/study to]',
        channel: 'Lofi Girl',
        verified: true,
        date: '1 year ago',
        duration: '6:32:05',
        link: `https://www.youtube.com/watch?v=n61ULEU7CO0`,
        thumbnail: `https://i.ytimg.com/vi/n61ULEU7CO0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAi4TCpAtbxLFIBULRlcZHudl1uFw`,
        channel_avatar: `https://yt3.ggpht.com/pcvnEbQ1F18Oms0Dn4qBf7APYU4Uj_AiJZAl023Z6ZBeSU7R8gq41DGMYgb1hBVhdK6GZeD6=s48-c-k-c0x00ffffff-no-rj`,
        views: '26M',
    },
    {
        name: `Relaxing Sleep Music with Rain Sounds | Cures for Anxiety Disorders, Piano Music, Calm Down & Relax`,
        channel: 'The Soul of Wind',
        verified: true,
        date: '2 months ago',
        duration: '23:06:02',
        link: `https://www.youtube.com/watch?v=VYJGMftYtY4`,
        thumbnail: `https://i.ytimg.com/vi/VYJGMftYtY4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAN6-_vwDTatvvzpeSNepd18T1eZA`,
        channel_avatar: `https://yt3.ggpht.com/ytc/AOPolaTABrRPPp31Z2AjTrUAiUanfpuzt2ZSdAGm04LuKA=s68-c-k-c0x00ffffff-no-rj`,
        views: '470K',
    },
    {
        name: `Relax Day 🌳 Lofi Keep You Safe 🍃 Lofi Hip Hop Radio ~ Chill Mix [Relax - Calm - Chill ]`,
        channel: 'LOFI KEEP YOU SAFE',
        verified: false,
        date: '2 months ago',
        duration: '11:55:56',
        link: `https://www.youtube.com/watch?v=9qM9YGI-XbM`,
        thumbnail: `https://i.ytimg.com/vi/9qM9YGI-XbM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrQEocKxp6iV0wO_L0paxUEKVLLQ`,
        channel_avatar: `https://yt3.ggpht.com/XDY_UbfPTh8MaRSFAihPDdHnjwDR4Qwx7XHJYBpGNrrztOKqD2VTbmzy8gu9vaTOkHeBMuRqfUo=s68-c-k-c0x00ffffff-no-rj`,
        views: '19K',
    },
    {
        name: 'Best of lofi hip hop 2021 ✨ [beats to relax/study to]',
        channel: 'Lofi Girl',
        verified: true,
        date: '1 year ago',
        duration: '6:32:05',
        link: `https://www.youtube.com/watch?v=n61ULEU7CO0`,
        thumbnail: `https://i.ytimg.com/vi/n61ULEU7CO0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAi4TCpAtbxLFIBULRlcZHudl1uFw`,
        channel_avatar: `https://yt3.ggpht.com/pcvnEbQ1F18Oms0Dn4qBf7APYU4Uj_AiJZAl023Z6ZBeSU7R8gq41DGMYgb1hBVhdK6GZeD6=s48-c-k-c0x00ffffff-no-rj`,
        views: '26M',
    },
    {
        name: `Relaxing Sleep Music with Rain Sounds | Cures for Anxiety Disorders, Piano Music, Calm Down & Relax`,
        channel: 'The Soul of Wind',
        verified: true,
        date: '2 months ago',
        duration: '23:06:02',
        link: `https://www.youtube.com/watch?v=VYJGMftYtY4`,
        thumbnail: `https://i.ytimg.com/vi/VYJGMftYtY4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAN6-_vwDTatvvzpeSNepd18T1eZA`,
        channel_avatar: `https://yt3.ggpht.com/ytc/AOPolaTABrRPPp31Z2AjTrUAiUanfpuzt2ZSdAGm04LuKA=s68-c-k-c0x00ffffff-no-rj`,
        views: '470K',
    },
    {
        name: `Relax Day 🌳 Lofi Keep You Safe 🍃 Lofi Hip Hop Radio ~ Chill Mix [Relax - Calm - Chill ]`,
        channel: 'LOFI KEEP YOU SAFE',
        verified: false,
        date: '2 months ago',
        duration: '11:55:56',
        link: `https://www.youtube.com/watch?v=9qM9YGI-XbM`,
        thumbnail: `https://i.ytimg.com/vi/9qM9YGI-XbM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrQEocKxp6iV0wO_L0paxUEKVLLQ`,
        channel_avatar: `https://yt3.ggpht.com/XDY_UbfPTh8MaRSFAihPDdHnjwDR4Qwx7XHJYBpGNrrztOKqD2VTbmzy8gu9vaTOkHeBMuRqfUo=s68-c-k-c0x00ffffff-no-rj`,
        views: '19K',
    },
    {
        name: 'Best of lofi hip hop 2021 ✨ [beats to relax/study to]',
        channel: 'Lofi Girl',
        verified: true,
        date: '1 year ago',
        duration: '6:32:05',
        link: `https://www.youtube.com/watch?v=n61ULEU7CO0`,
        thumbnail: `https://i.ytimg.com/vi/n61ULEU7CO0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAi4TCpAtbxLFIBULRlcZHudl1uFw`,
        channel_avatar: `https://yt3.ggpht.com/pcvnEbQ1F18Oms0Dn4qBf7APYU4Uj_AiJZAl023Z6ZBeSU7R8gq41DGMYgb1hBVhdK6GZeD6=s48-c-k-c0x00ffffff-no-rj`,
        views: '26M',
    },
    {
        name: `Relaxing Sleep Music with Rain Sounds | Cures for Anxiety Disorders, Piano Music, Calm Down & Relax`,
        channel: 'The Soul of Wind',
        verified: true,
        date: '2 months ago',
        duration: '23:06:02',
        link: `https://www.youtube.com/watch?v=VYJGMftYtY4`,
        thumbnail: `https://i.ytimg.com/vi/VYJGMftYtY4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAN6-_vwDTatvvzpeSNepd18T1eZA`,
        channel_avatar: `https://yt3.ggpht.com/ytc/AOPolaTABrRPPp31Z2AjTrUAiUanfpuzt2ZSdAGm04LuKA=s68-c-k-c0x00ffffff-no-rj`,
        views: '470K',
    },
    {
        name: `Relax Day 🌳 Lofi Keep You Safe 🍃 Lofi Hip Hop Radio ~ Chill Mix [Relax - Calm - Chill ]`,
        channel: 'LOFI KEEP YOU SAFE',
        verified: false,
        date: '2 months ago',
        duration: '11:55:56',
        link: `https://www.youtube.com/watch?v=9qM9YGI-XbM`,
        thumbnail: `https://i.ytimg.com/vi/9qM9YGI-XbM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrQEocKxp6iV0wO_L0paxUEKVLLQ`,
        channel_avatar: `https://yt3.ggpht.com/XDY_UbfPTh8MaRSFAihPDdHnjwDR4Qwx7XHJYBpGNrrztOKqD2VTbmzy8gu9vaTOkHeBMuRqfUo=s68-c-k-c0x00ffffff-no-rj`,
        views: '19K',
    },
    {
        name: 'Best of lofi hip hop 2021 ✨ [beats to relax/study to]',
        channel: 'Lofi Girl',
        verified: true,
        date: '1 year ago',
        duration: '6:32:05',
        link: `https://www.youtube.com/watch?v=n61ULEU7CO0`,
        thumbnail: `https://i.ytimg.com/vi/n61ULEU7CO0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAi4TCpAtbxLFIBULRlcZHudl1uFw`,
        channel_avatar: `https://yt3.ggpht.com/pcvnEbQ1F18Oms0Dn4qBf7APYU4Uj_AiJZAl023Z6ZBeSU7R8gq41DGMYgb1hBVhdK6GZeD6=s48-c-k-c0x00ffffff-no-rj`,
        views: '26M',
    },
    {
        name: `Relaxing Sleep Music with Rain Sounds | Cures for Anxiety Disorders, Piano Music, Calm Down & Relax`,
        channel: 'The Soul of Wind',
        verified: true,
        date: '2 months ago',
        duration: '23:06:02',
        link: `https://www.youtube.com/watch?v=VYJGMftYtY4`,
        thumbnail: `https://i.ytimg.com/vi/VYJGMftYtY4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAN6-_vwDTatvvzpeSNepd18T1eZA`,
        channel_avatar: `https://yt3.ggpht.com/ytc/AOPolaTABrRPPp31Z2AjTrUAiUanfpuzt2ZSdAGm04LuKA=s68-c-k-c0x00ffffff-no-rj`,
        views: '470K',
    },
    {
        name: `Relax Day 🌳 Lofi Keep You Safe 🍃 Lofi Hip Hop Radio ~ Chill Mix [Relax - Calm - Chill ]`,
        channel: 'LOFI KEEP YOU SAFE',
        verified: false,
        date: '2 months ago',
        duration: '11:55:56',
        link: `https://www.youtube.com/watch?v=9qM9YGI-XbM`,
        thumbnail: `https://i.ytimg.com/vi/9qM9YGI-XbM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrQEocKxp6iV0wO_L0paxUEKVLLQ`,
        channel_avatar: `https://yt3.ggpht.com/XDY_UbfPTh8MaRSFAihPDdHnjwDR4Qwx7XHJYBpGNrrztOKqD2VTbmzy8gu9vaTOkHeBMuRqfUo=s68-c-k-c0x00ffffff-no-rj`,
        views: '19K',
    },

]

export { videoList }